version: "3.6"

services:
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
